### ISSUE TITLE
Publish artifacts for 2.5.0

### ISSUE THREAD

**Issue by vaclavsvejcar** [josephpconley/play-jsonpath#11]
Hi, it seems that artifact for the newest version of your library (2.5.0) are not published into Maven. Could you please publish them? Thanks.

http://repo1.maven.org/maven2/com/josephpconley/play-jsonpath_2.11/

**Comment by ferranjr** [comment]
+1

**Comment by josephpconley** [comment]
I'll take a look this week, thanks guys!

**Comment by ferranjr** [comment]
Thanks! that would be great!

**Comment by josephpconley** [comment]
Just published a 2.5.0 version for Scala 2.11, should take a few minutes to propagate.  Play did not publish a Scala 2.10 version for play-json 2.5.x so I won't be doing that either.

**Comment by josephpconley** [comment]
Confirmed.

**Comment by ferranjr** [comment]
thanks @josephpconley
