### ISSUE TITLE
Figure out cross-version issue

### ISSUE THREAD

**Issue by josephpconley** [josephpconley/play-jsonpath#2]
1.0 requires 2.10 Scala, should make the library version-independent (if possible)

**Comment by chenbekor** [comment]
what is the status with this issue? is there a release that supports cross version compilations?

the maven central repo holds only ver 1.0 - I noticed that there was some pull request merge that should resolve the issue. Any help is appreciated!

**Comment by josephpconley** [comment]
Hi @chenbekor, I tested out a version with the pull request merged and ran into some issues with Play versioning, I'll take a look at the Play versioning issues this week, will keep you posted.

**Comment by chenbekor** [comment]
@josephpconley this is great news. it is super urgent for us,  as soon as you have some results we will be glad to try it out. cheers!

**Comment by josephpconley** [comment]
@chenbekor just released 1.1 to maven central which has both 2.10 and 2.11, this should address this issue.
