### ISSUE TITLE
Upgrade to Play 2.4, sync up versioning with Play?

### ISSUE THREAD

**Issue by josephpconley** [josephpconley/play-jsonpath#4]
Play recently upgraded to 2.4.x, [changing the JSON API](https://playframework.com/documentation/2.4.x/Migration24#JSON-API-changes).  This is a breaking change, we'll need to update the `JSONPath` code to accommodate.  

Also, if this is to strictly be a Play wrapper (and not a generic JSONPath wrapper for multiple libraries) it might be a good idea to sync the versioning with Play.

**Comment by chenbekor** [comment]
please make sure to leave support for 2.3.x since some users are not porting to 2.4.x just yet.

**Comment by josephpconley** [comment]
Yep will do, I certainly haven't ported yet and I have a few apps using this so I'm not in any rush :)

**Comment by clescot** [comment]
Hi,
any update on this issue?
best regards,

Charles.

**Comment by josephpconley** [comment]
I'll take a look at it this week, if you're interested in fixing feel free to send me a PR :)

**Comment by jCalamari** [comment]
> I'll take a look at it this week, if you're interested in fixing feel free to send me a PR :)

Hi, Any luck with 2.4?

**Comment by josephpconley** [comment]
Trying to clean up the versioning first to sync up with Play's versioning, once that's done I'll cut a 2.4 release.  Hopefully sooner than later.

**Comment by josephpconley** [comment]
This issue should be addressed with recent 2.4.0 release per #7.  Please verify that you can grab the 2.4.0 release.
